'use client'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
if('serviceWorker' in navigator){
  navigator.serviceWorker.register('/service-worker.js',{scope:'/'})
  .then((registration)=>{
    console.log('Service worker registered sucessfully . Scope',registration.scope)
  }).catch((error)=>{
    console.log('Service worker registration failed:',error)
  })
}
console.log('layout')
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='manifest' href='/manifest.json'/>
      </head>
      <body className={inter.className}>
      <button id="install-button" style={{display:'none'}}>Install App</button>
        {children}</body>
    </html>
  )
}
